from __future__ import annotations

from datetime import datetime
from ipaddress import IPv4Address, IPv6Address
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field

from sentinellab.models.security_event import EventSeverity


class SecurityAlert(BaseModel):
    """Alert generated by a SentinelLab detection rule."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )

    alert_id: UUID = Field(default_factory=uuid4)

    timestamp: datetime

    rule_id: str
    rule_name: str

    severity: EventSeverity

    description: str

    source_ip: IPv4Address | IPv6Address

    event_count: int = Field(ge=1)

    first_event_timestamp: datetime
    last_event_timestamp: datetime

    event_ids: list[UUID] = Field(default_factory=list)
